### ISSUE TITLE
Pathfinding tuning: Includes testing out other pathfinding planners, including RRT*, RRTX, PRM*, Informed RRT

### ISSUE THREAD

**Issue by tylerlum** [UBCSailbot/local-pathfinding#123]

**Comment by tylerlum** [comment]
Something like

`roslaunch local_pathfinding all.launch planner_type:=RRTStar`

**Comment by tylerlum** [comment]
Can also set the random_seed parameter as well

Characterize qualitatively and quantiatively
* How long it takes to generate paths
* How good are the paths
* How many times it fails to find a path
* How many times it creates a very bad path

**Comment by tylerlum** [comment]
Look at https://github.com/UBCSailbot/local-pathfinding/blob/master/python/Path.py

def createPath(state, runtimeSeconds=1.0, numRuns=2, resetSpeedupDuringPlan=False, speedupBeforePlan=1.0,)

Play around with runtimeSeconsd and numRuns

**Comment by tylerlum** [comment]
rostopic pub /changeGlobalWind sailbot_msg/globalWind "directionDegrees: 45.0
speedKmph: 0.0"

to change the wind and push the boat harder

**Comment by tylerlum** [comment]
rostopic pub /boat_on_path local_pathfinding/addBoat "addType: 'onBoat'            
ship: {ID: 0, lat: 0.0, lon: 0.0, headingDegrees: 0.0, speedKmph: 0.1}
waypointIndex: 0"

rostopic pub /boat_on_path local_pathfinding/addBoat "addType: 'trailing'     
ship: {ID: 0, lat: 0.0, lon: 0.0, headingDegrees: 0.0, speedKmph: 1.0}
waypointIndex: 0"


To put a new boat on or behind our boat.

**Comment by tylerlum** [comment]
The code for adjusting how much obstacles are projected (moved forward) and extended (stretched forward) https://github.com/UBCSailbot/local-pathfinding/blob/master/python/obstacles.py#L11

**Comment by tylerlum** [comment]
Related: #86

**Comment by tylerlum** [comment]
AIS_BOAT_RADIUS_KM = 0.2
Probably should be increased to at least 0.5 to really avoid hitting boats.

**Comment by tylerlum** [comment]
Pathfinding planner used here:
```
python/updated_geometric_planner.py
```

**Comment by tylerlum** [comment]
Can test with "toy" integration tests by following instructions at:
https://github.com/UBCSailbot/local-pathfinding/tree/master/json

**Comment by JoshuaJSam** [comment]
Testing with the launch parameters:

    <arg name="num_ais_ships" default="15" />
    <arg name="random_seed" default="123" />

and trying out different pathfinding algorithms

   <arg name="planner_type" default="rrtxstatic" />

Also useful to change parameters in obstacles.py

   AIS_BOAT_RADIUS_KM = 0.2

and in MOCK_wind_sensor.py

   globalWindDirectionDegrees = 45

ends up creating a test case where the sailbot is trying to path around another boat which is travelling perpendicular to the path of the sailbot. It causes the sailbot to get into a cyclical loop of generating new bad paths which does not avoid the other boat, but continues to be in the path of the boat. 

![prmstar](https://user-images.githubusercontent.com/47064054/104821983-7ca8b500-57f4-11eb-96e5-6bfde14f09be.gif)

**Comment by tylerlum** [comment]
Great work and analysis done in #220
