### ISSUE TITLE
Integrate real AIS data

### ISSUE THREAD

**Issue by tylerlum** [UBCSailbot/local-pathfinding#124]

**Comment by tylerlum** [comment]
"""
The API instructions PDF was sent by Richard (check email). If you can read over it and implement it, that'd be great! Any technical questions you can directly ask the exactEarth folks (Richard and Zach)
"""
From Simon

**Comment by tylerlum** [comment]
[exactAIS Geospatial Web Services Specification Document v. 3.1.pdf](https://github.com/UBCSailbot/local-pathfinding/files/6053498/exactAIS.Geospatial.Web.Services.Specification.Document.v.3.1.pdf)

**Comment by haakov** [comment]
From the PDF:

[The URL below] provides a JSON output for 10 vessels within a specific area of interest from the
latest vessel information data set.

```
https://services.exactearth.com/gws/wms?service=WFS&version=1.1.0&request=GetFeature&typeName=exactAIS:LVI&outputFo
rmat=json&maxFeatures=10&filter=<Filter
xmlns:gml="http://www.opengis.net/gml"><Intersects><PropertyName>position</PropertyName><gml:Polygon
xmlns:gml="http://www.opengis.net/gml" srsName="EPSG:4326"><gml:exterior><gml:LinearRing><gml:posList>-55 -8 -55 8 55 8
55 -8 -55 -8</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon></Intersects></Filter>
```

The posList consists of 5 coordinate tuples, where the first and last must be coincident

**Comment by tylerlum** [comment]
![image](https://user-images.githubusercontent.com/26510814/111042455-5c5f3600-83f2-11eb-95a6-d77bf8488f1b.png)

**Comment by tylerlum** [comment]
[Esri ArcMap 10.3.1 - WMS Setup Guide.pdf](https://github.com/UBCSailbot/local-pathfinding/files/6135442/Esri.ArcMap.10.3.1.-.WMS.Setup.Guide.pdf)

[exactAIS Geospatial Web Services Specification Document v. 3.1.pdf](https://github.com/UBCSailbot/local-pathfinding/files/6135443/exactAIS.Geospatial.Web.Services.Specification.Document.v.3.1.pdf)

[Quantum GIS - Setup Guide.pdf](https://github.com/UBCSailbot/local-pathfinding/files/6135444/Quantum.GIS.-.Setup.Guide.pdf)

**Comment by tylerlum** [comment]
Username, Password, GWS Token information is on Slack #general-software channel

**Comment by tylerlum** [comment]
Implementation completed by @haakov in #225 :)

`roslaunch local_pathfinding all.launch AIS_token:=<token>` to use exactAIS or just `roslaunch local_pathfinding all.launch` to run with default
