### ISSUE TITLE
Add summarization of a run

### ISSUE THREAD

**Issue by tylerlum** [UBCSailbot/local-pathfinding#129]
Right now, we can run a simulation and see the results. We have lots of logging being done, which is great. However, we should try to get a summary of important takeaways based on each run:

Eg. Total time. Total Distance covered. # of bad paths. Worst path created. Closest we got to an obstacle. Plot of distance to closest obstacle over the whole run. Number of collisions. Number of times pathfinding couldn't find a path in time.

This can be shown visually or with a text file or even printed to the screen at the end.

**Comment by tylerlum** [comment]
Breaking this into a few specific different tasks. Note: for an example of an independent ros node, look at https://github.com/UBCSailbot/local-pathfinding/blob/master/python/addBoat.py

1. Create an independent ros node that subscribes to the sailbot GPS and AIS boat locations. Then finds which AIS boat is closest to our boat, calculate that distance, and then store the distance and time in a text file. Repeat this every second (can make a constant UPDATE_TIME_SECONDS = 1.0 that can be modified). When the simulation ends, we will have a .txt file (or something similar) that allows us to plot distance vs. time through the run. Perhaps even save a plot of this, rather than saving to a text file.

2. Create an independent ros node that subscribes to the sailbot GPS. Every second (can make a constant UPDATE_TIME_SECONDS = 1.0 that can be modified), store the sailbot GPS. Then at the end, plot the distance traveled over time OR displacement from initial position over time OR plot the full path that the boat took (see how jagged or uneven it is).

3. Go to https://github.com/UBCSailbot/local-pathfinding/blob/master/python/Path.py#L774

**Comment by tylerlum** [comment]
@haakov @JoshuaJSam @patrick-5546 please comment here which part you plan to work on once you decide so you don't double up on the same task

**Comment by patrick-5546** [comment]
I can do part 5

**Comment by JoshuaJSam** [comment]
Part 2 looks interesting! I'd like to get some experience working on my own ROS node :)

**Comment by haakov** [comment]
I'm doing 1 and 3

**Comment by tylerlum** [comment]
I'm doing number 4

**Comment by patrick-5546** [comment]
I'll do 1

**Comment by patrick-5546** [comment]
I'll do 3

**Comment by patrick-5546** [comment]
All 5 tasks complete :)
