### ISSUE TITLE
Measured wind using wind sensor may have problems, especially if there is noise in sensors

### ISSUE THREAD

**Issue by tylerlum** [UBCSailbot/local-pathfinding#146]
We calculate global wind based on wind sensor and GPS and IMU data. If there is noise, this measurement will be bad, which could cause the boat to go in an infinite loop of panic, plan new path, and turn, and then panic again.

**Comment by tylerlum** [comment]
Consider rolling average or exponential weighted average.

**Comment by patrick-5546** [comment]
Discussion continued in #256
