### ISSUE TITLE
Fix global waypoint reached normal line

### ISSUE THREAD

**Issue by tylerlum** [UBCSailbot/local-pathfinding#180]
Right now, the global waypoint reached function checks if the boat has cross the normal line between the second last local waypoint and the last local waypoint. However, this is not robust to big changes in GPS, as the path would then change. The proper solution is the set this normal line between the PREVIOUS GLOBAL WAYPOINT and the CURRENT GLOBAL WAYPOINT.

**Comment by tylerlum** [comment]
To reproduce:
```
roslaunch local_pathfinding all.launch random_seed:=100
```
![image](https://user-images.githubusercontent.com/26510814/107873756-a42d8480-6e69-11eb-81e9-1973ad969986.png)
^ should start like this

In different terminal run:
```
rostopic pub /changeGPS sailbot_msg/GPS "lat: 47.9
lon: -125.8
headingDegrees: 0.0
speedKmph: 20.0"
```
(don't copy and paste, but type, tab, auto complete, then change numbers, else the white space may not work)
![image](https://user-images.githubusercontent.com/26510814/107873773-c6270700-6e69-11eb-9499-4eea01db81f6.png)

**Comment by patrick-5546** [comment]
I also noticed that it does not seem to be working. Even when I moved the waypoint reached line back and decreased the speedup (I tried with `initial_speedup=10`), the boat would cross the line by quite a bit.

![Screenshot from 2021-02-14 17-40-25](https://user-images.githubusercontent.com/65756895/107896809-40986b00-6eec-11eb-9f7a-67dd27e1afce.png)

**Comment by tylerlum** [comment]
![Uploading IMG_20210218_110528903.jpg…]()

**Comment by tylerlum** [comment]
![IMG_20210218_111020197](https://user-images.githubusercontent.com/26510814/108408536-fe1baa80-71d9-11eb-8fa5-07faad21f68f.jpg)
