### ISSUE TITLE
Discretize state space

### ISSUE THREAD

**Issue by tylerlum** [UBCSailbot/local-pathfinding#194]
Right now, we have a continuous state space. This is okay, but can make the pathfinding slow and/or find relatively poor solutions. We don't need too much resolution. Probably just a grid of points 1km apart or so. This would allow for simple 45 degree and 90 degree turns very easily.

This code is currently in updated_geometric_planner.py

def plan(run_time, planner_type, wind_direction_degrees, dimensions, start_pos, goal_pos, obstacles, heading_degrees,
         objective_type='WeightedLengthAndClearanceCombo'):
    # Construct the robot state space in which we're planning
    space = ob.SE2StateSpace()

    # Create bounds on the position
    bounds = ob.RealVectorBounds(2)
    x_min, y_min, x_max, y_max = dimensions
    bounds.setLow(0, x_min)
    bounds.setLow(1, y_min)
    bounds.setHigh(0, x_max)
    bounds.setHigh(1, y_max)
    space.setBounds(bounds)

    # Define a simple setup class
    ss = og.SimpleSetup(space)

This shows the setup of the continuous state space, but can probably be improved.

OMPL Documentation
https://ompl.kavrakilab.org/spaces.html
https://ompl.kavrakilab.org/classompl_1_1base_1_1SE2StateSpace.html
https://ompl.kavrakilab.org/api_overview.html
https://ompl.kavrakilab.org/classompl_1_1base_1_1CompoundStateSpace.html
https://ompl.kavrakilab.org/classompl_1_1base_1_1DiscreteStateSpace.html

OMPL Example Code
https://github.com/ompl/ompl/tree/main/demos
https://github.com/ompl/ompl/blob/main/demos/OptimalPlanning.py
https://github.com/ompl/ompl/blob/main/demos/StateSampling.py

**Comment by JoshuaJSam** [comment]
Working branch here:

https://github.com/UBCSailbot/local-pathfinding/tree/improve_pathing

**Comment by tylerlum** [comment]
Implemented in #212
