### ISSUE TITLE
Update and test ROS interface node

### ISSUE THREAD

**Issue by tylerlum** [UBCSailbot/local-pathfinding#199]
1. the sensor.msg type has been updated, so we should update our code to reflect this
2. We should setup a mock sensor output to actually pass sensor values through this interface and make sure the data flow is working

**Comment by tylerlum** [comment]
Questions
* What are degree minutes? 
* What is difference between ais and can gps?
* Should we use the accelerometer and gyroscope data? How good are these sensors?

**Comment by tylerlum** [comment]
Create a MOCK sensor.msg node. Can be like python/MOCK_global_planner.py. Initially can just output hard-coded constants, just to test that data flows properly from the interface node.

**Comment by patrick-5546** [comment]
> * What are degree minutes?

[Typical coordinate units](https://gis.stackexchange.com/questions/228562/what-units-are-used-for-coordinates-in-geographic-and-projected-coordinate-syste/228563)
[Degree minutes to decimal degrees](https://www.directionsmag.com/site/latlong-converter/)

**Comment by tylerlum** [comment]
New updates:
* Degree minutes are being changed to just degrees now
* We need to convert the heading_degrees and wind angles to match this convention

Probably just change it when we output and input (not worth changing it everywhere)
![image](https://user-images.githubusercontent.com/26510814/120973874-598b8d00-c724-11eb-88bc-851798c3c78b.png)
