### ISSUE TITLE
Handle global wind speed is 0

### ISSUE THREAD

**Issue by tylerlum** [UBCSailbot/local-pathfinding#270]
When global wind speed is 0, then the direction is measningless. However, we look at the direction wrt the boat's path direction to decide if we are upwind/downwind. THEREFORE, we should have a check that says no upwind/downwind if global wind speed is 0.

**Comment by tylerlum** [comment]
Also, ensure we handle the 0 global wind speed situation correctly in general.

**Comment by patrick-5546** [comment]
### Relevant code

https://github.com/UBCSailbot/local-pathfinding/blob/5259485a46a1b11c73f961a503d20eb9f8401c9f/python/main_loop.py#L115-L117

- This function is defined in `Path.py`

**Comment by patrick-5546** [comment]
> Also, ensure we handle the 0 global wind speed situation correctly in general.

What needs to be checked?

**Comment by tylerlum** [comment]
When wind speed is 0, the wind direction is ambiguous. 0 length vector has no direction. Therefore, the planning that uses wind direction might be kinda dumb (may think it's going upwind or downwind, when it does not).

**Comment by patrick-5546** [comment]
Could use a threshold instead of just 0.; see #271

**Comment by patrick-5546** [comment]
Brainstorming:
- If there is low wind, never update local path
- But maybe there are some other options that we can think about

**Comment by jamenkaye** [comment]
Current plan: make a low wind threshold below which the local path doesn't get updated. Also, this threshold ideally would depend on the wind direction compared to the direction we're trying to sail in. The threshold should be lower for downwind sailing, because we will still be floating in the right direction. Currently thinking the threshold should be 3knots ish, but this should be tuned after on water testing.

**Comment by patrick-5546** [comment]
Add filtering logic in ros_interface.py so that it can be used for both pathfinding and controls

**Comment by jamenkaye** [comment]
Expected speed of raye in m/s as a function of wind angle for different wind speeds
![raye_vpp_estimated](https://user-images.githubusercontent.com/71156197/154817031-2271e4b3-1f2b-4a6b-9367-783cfd574cb1.jpg)
.
